threshold: 10
errors:
  - clicker.heroes.acg@gmail.com
alerts:
  suppress:
    - on-found-puzzle
    - on-lost-puzzle
    - on-scope
  github:
    - l3r8yJ
format:
  - short-title
  - title-length=100
tags:
  - pdd
  - bug